[tool.ruff]
# 1. 指定要启用的规则代码
#    这里示范：再加 D（pydocstyle）、N（命名规范）、UP（pyupgrade）
select = [
    "E",   # pycodestyle 错误
    "F",   # pyflakes
    "W",   # pycodestyle 警告
    "I",   # isort (import 排序)
    "D",   # pydocstyle（docstring）
    "N",   # naming convention
    "UP",  # pyupgrade（升级语法）
]

# 2. 明确排除的目录
extend-exclude = [
    "backend/alembic",
    "backend/db",
    ".venv",
    "__pycache__",
]

# 3. 针对单文件忽略特定规则
[tool.ruff.per-file-ignores]
"tests/*" = ["D"]        # 测试文件不要求写 docstring
"backend/alembic/env.py" = ["E402", "F401"]